name: build
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            # git-revision-date-localized-plugin and mkdocs-rss-plugin need full git history depth
            fetch-depth: 0
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - uses: actions/cache@v3
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-
        - name: Install dependencies
          working-directory: .
          run: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install -r requirements.txt
        - name: Build docs
          working-directory: .
          run: |
            mkdocs build
        - name: Validate generated HTML files
          working-directory: .
          run: |
            linkcheckMarkdown -v -r ./docs
        # On push to main or release branch, deploy docs
        - name: Set up git author
          if: ${{ inputs.deploy }}
          run: |
            remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git remote rm origin
            git remote add origin "${remote_repo}"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Deploy docs (Main)
          if: ${{ github.ref == 'refs/heads/main' && inputs.deploy }}
          working-directory: .
          run: |
            # echo "${CUSTOM_DOMAIN}" > "${GITHUB_WORKSPACE}/docs/CNAME"
            echo -e "User-agent: *\nDisallow: /v*.*/\nSitemap: https://${CUSTOM_DOMAIN}/sitemap.xml" > "${GITHUB_WORKSPACE}/docs/robots.txt"
            git fetch origin gh-pages --verbose
            mike deploy main dev --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase
          env:
            CUSTOM_DOMAIN: "???"
        - name: Deploy docs (Versions)
          if: ${{ startsWith(github.ref, 'refs/tags/v') && inputs.deploy }}
          run: |
            git fetch origin gh-pages --verbose
            mike deploy ${GITHUB_REF##*/} latest --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase --update-aliases