name: mkdocs

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    tags:
      - 'v*'
jobs:
  check:
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
    with:
      deploy: true